title: Semantic Line Breaks
email: info@sembr.org
description: >-
  When writing text with a compatible markup language,
  add a line break after each substantial unit of thought.
url: https://sembr.org
github_username: sembr

markdown: ExtendedCommonMark
commonmark:
  options: ["SMART", "UNSAFE"]
  extensions: ["autolink"]

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: specification/README.md
    values:
      permalink: "/"

include:
  - .well-known
  - specification/README.md

exclude:
  - Gemfile
  - Gemfile.lock

assets:
  source_maps: true
  compression: true
  defaults:
    js: { integrity: true }
    css: { integrity: true }
    img: { integrity: true }
